"""Initial Migrate

Revision ID: 11bf5e3e196c
Revises: a5dd37a9274e
Create Date: 2025-04-01 00:06:25.049958

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '11bf5e3e196c'
down_revision = 'a5dd37a9274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
