"""Initial Migrate

Revision ID: 30388d2d32c0
Revises: ad38ec67331e
Create Date: 2025-03-31 23:57:04.868019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector


# revision identifiers, used by Alembic.
revision = '30388d2d32c0'
down_revision = 'ad38ec67331e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'embedding')
    # ### end Alembic commands ###
