"""Initial Migrate

Revision ID: 35832939a289
Revises: 5f87e0846246
Create Date: 2025-04-02 20:27:55.908291

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
import pgvector
# revision identifiers, used by Alembic.
revision = '35832939a289'
down_revision = '5f87e0846246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_id'), 'embedding', ['id'], unique=False)
    op.create_index('ix_metadata_gin', 'embedding', ['cmetadata'], unique=False, postgresql_using='gin', postgresql_ops={'cmetadata': 'jsonb_path_ops'})
    op.drop_index('ix_document_id', table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name='document_upload_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    op.create_index('ix_document_id', 'document', ['id'], unique=False)
    op.drop_index('ix_metadata_gin', table_name='embedding', postgresql_using='gin', postgresql_ops={'cmetadata': 'jsonb_path_ops'})
    op.drop_index(op.f('ix_embedding_id'), table_name='embedding')
    op.drop_table('embedding')
    # ### end Alembic commands ###
