"""refactor(models): change tenant_id、status nullable

Revision ID: 3bb19e196b09
Revises: c1d5fb755eb9
Create Date: 2025-04-26 18:32:25.179196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bb19e196b09'
down_revision = 'c1d5fb755eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('ENABLE', 'DISABLE', 'EXPIRED', 'PENDING', 'LOCKED', 'HIDDEN', name='statustypes'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('ENABLE', 'DISABLE', 'EXPIRED', 'PENDING', 'LOCKED', 'HIDDEN', name='statustypes'),
               nullable=True)
    # ### end Alembic commands ###
