"""Initial Migrate

Revision ID: 3e7933877b35
Revises: 4d0567473048
Create Date: 2025-03-29 06:23:38.144100

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3e7933877b35'
down_revision = '4d0567473048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'apikey', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.drop_column('apikey', 'owner_id')
    # ### end Alembic commands ###
