"""add phone and avatar on user models

Revision ID: 44254f6edfd8
Revises: 8159f5133429
Create Date: 2025-04-26 12:47:46.593266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44254f6edfd8'
down_revision = '8159f5133429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding', 'embedding')
    op.drop_column('team', 'workflow')
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'phone')
    op.add_column('team', sa.Column('workflow', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('embedding', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
