"""Initial Migrate

Revision ID: 455dde5ecaa6
Revises: c2cb98ae2690
Create Date: 2025-04-01 02:28:42.067633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '455dde5ecaa6'
down_revision = 'c2cb98ae2690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectordocument', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('vectordocument', sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vectordocument', 'text_content')
    op.drop_column('vectordocument', 'chunk_index')
    # ### end Alembic commands ###
