"""Initial Migrate

Revision ID: 4699f88a4d8b
Revises: 7dd47f1885d8
Create Date: 2025-03-31 02:35:00.837677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4699f88a4d8b'
down_revision = '7dd47f1885d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
