"""Initial Migrate

Revision ID: 4f59f1e57f29
Revises: 11bf5e3e196c
Create Date: 2025-04-01 00:08:23.550727

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f59f1e57f29'
down_revision = '11bf5e3e196c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
