"""refactor(models): change tenant_id、status nullable

Revision ID: 579c70c77151
Revises: 3bb19e196b09
Create Date: 2025-05-01 01:34:18.778966

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '579c70c77151'
down_revision = '3bb19e196b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apikey', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dictionary_arguments', 'sort',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('graph', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('invite_codes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('invite_codes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('invite_codes', sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.add_column('team_user_join', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_user_join', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_user_join', sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.add_column('tenant', sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tenant', 'max_teams')
    op.drop_column('tenant', 'max_storage_gb')
    op.drop_column('tenant', 'max_users')
    op.alter_column('thread', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('upload', 'last_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('thread', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tenant', sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tenant', sa.Column('max_storage_gb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('tenant', sa.Column('max_teams', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tenant', 'public_key')
    op.drop_column('team_user_join', 'remark')
    op.drop_column('team_user_join', 'updated_at')
    op.drop_column('team_user_join', 'created_at')
    op.drop_column('invite_codes', 'remark')
    op.drop_column('invite_codes', 'updated_at')
    op.drop_column('invite_codes', 'created_at')
    op.alter_column('graph', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dictionary_arguments', 'sort',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('apikey', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
