"""Initial Migrate

Revision ID: 667c9470f0cd
Revises: d6e014af89e6
Create Date: 2025-03-29 10:18:25.222976

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '667c9470f0cd'
down_revision = 'd6e014af89e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('thread', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'thread', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column('thread', 'owner_id')
    op.drop_column('skill', 'is_public')
    # ### end Alembic commands ###
