"""Initial Migrate

Revision ID: 6b20ac4e7825
Revises: 35832939a289
Create Date: 2025-04-03 01:48:42.048070

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b20ac4e7825'
down_revision = '35832939a289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.add_column('embedding', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'embedding', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'embedding', 'team', ['team_id'], ['id'])
    op.add_column('model', sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('model', 'metadata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('model', 'cmetadata')
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.drop_constraint(None, 'embedding', type_='foreignkey')
    op.drop_column('embedding', 'team_id')
    op.drop_column('embedding', 'owner_id')
    # ### end Alembic commands ###
