"""Add column language to User model

Revision ID: 712ee0950c10
Revises: a028b69662a5
Create Date: 2025-03-28 15:04:57.754815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '712ee0950c10'
down_revision = 'a028b69662a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
