"""Initial Migrate

Revision ID: 7820980d8cef
Revises: 97f2a3915951
Create Date: 2025-03-31 03:41:13.173468

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7820980d8cef'
down_revision = '97f2a3915951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('upload', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('upload', sa.Column('file_size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'file_size')
    op.drop_column('upload', 'file_path')
    op.drop_column('upload', 'file_type')
    # ### end Alembic commands ###
