"""Initial Migrate

Revision ID: 7dd47f1885d8
Revises: c540f06c1aa7
Create Date: 2025-03-31 01:03:50.575161

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7dd47f1885d8'
down_revision = 'c540f06c1aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'file_path')
    op.drop_column('upload', 'file_size')
    op.drop_column('upload', 'file_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('upload', sa.Column('file_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('upload', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
