"""Initial Migrate

Revision ID: 7fff0ee670eb
Revises: 94b556780152
Create Date: 2025-04-01 00:12:08.882548

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7fff0ee670eb'
down_revision = '94b556780152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
