"""Alter owner_id nullable is true

Revision ID: 8159f5133429
Revises: 3b3e02de5504
Create Date: 2025-04-13 22:50:53.358603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8159f5133429'
down_revision = '3b3e02de5504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apikey', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('graph', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('member', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('model', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('modelprovider', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('skill', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('thread', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('upload', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('thread', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('skill', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('modelprovider', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('model', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('member', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('graph', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('apikey', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
