"""Initial Migrate

Revision ID: 94b556780152
Revises: 4f59f1e57f29
Create Date: 2025-04-01 00:11:21.426606

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '94b556780152'
down_revision = '4f59f1e57f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
