"""Initial Migrate

Revision ID: 97f2a3915951
Revises: 4699f88a4d8b
Create Date: 2025-03-31 03:00:39.014150

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97f2a3915951'
down_revision = '4699f88a4d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'status',
               existing_type=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED', name='uploadstatus'),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'status',
               existing_type=sa.Boolean(),
               type_=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED', name='uploadstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
