"""Initial Migrate

Revision ID: a5dd37a9274e
Revises: 30388d2d32c0
Create Date: 2025-04-01 00:01:33.919364

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a5dd37a9274e'
down_revision = '30388d2d32c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
