"""change phone and avatar default

Revision ID: ada9e5c94247
Revises: 44254f6edfd8
Create Date: 2025-04-26 12:49:20.473212

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ada9e5c94247'
down_revision = '44254f6edfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_phone', table_name='user')
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.create_index('ix_user_phone', 'user', ['phone'], unique=False)
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
