"""Initial Migrate

Revision ID: b7f0e4144e4e
Revises: d710f17b31ff
Create Date: 2025-03-29 20:27:41.811026

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b7f0e4144e4e'
down_revision = 'd710f17b31ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('belongs_to', sa.Uuid(), nullable=False))
    op.drop_constraint('unique_team_and_name', 'member', type_='unique')
    op.create_unique_constraint('unique_team_and_name', 'member', ['name', 'belongs_to'])
    op.drop_constraint('member_team_id_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'team', ['belongs_to'], ['id'])
    op.drop_column('member', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_team_id_fkey', 'member', 'team', ['team_id'], ['id'])
    op.drop_constraint('unique_team_and_name', 'member', type_='unique')
    op.create_unique_constraint('unique_team_and_name', 'member', ['name', 'team_id'])
    op.drop_column('member', 'belongs_to')
    # ### end Alembic commands ###
