"""Initial Migrate

Revision ID: bd8abdf6537e
Revises: 693bd98831b6
Create Date: 2025-03-29 17:48:02.257337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd8abdf6537e'
down_revision = '693bd98831b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
