"""Initial Migrate

Revision ID: bf59240f6553
Revises: 7fff0ee670eb
Create Date: 2025-04-01 00:17:38.714955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf59240f6553'
down_revision = '7fff0ee670eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
