"""Initial Migrate

Revision ID: c2cb98ae2690
Revises: f55a6400c287
Create Date: 2025-04-01 02:22:45.097482

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector

# revision identifiers, used by Alembic.
revision = 'c2cb98ae2690'
down_revision = 'f55a6400c287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vectordocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectordocument_id'), 'vectordocument', ['id'], unique=False)
    op.drop_column('upload', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vectordocument_id'), table_name='vectordocument')
    op.drop_table('vectordocument')
    # ### end Alembic commands ###
