"""Initial Migrate

Revision ID: c540f06c1aa7
Revises: 3c9408cc1832
Create Date: 2025-03-31 00:48:10.403173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c540f06c1aa7'
down_revision = '3c9408cc1832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('upload', sa.Column('file_size', sa.Float(), nullable=False))
    op.add_column('upload', sa.Column('is_build', sa.Boolean(), nullable=False))
    op.drop_column('upload', 'web_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('web_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('upload', 'is_build')
    op.drop_column('upload', 'file_size')
    op.drop_column('upload', 'file_path')
    # ### end Alembic commands ###
