"""Initial Migrate

Revision ID: c6dba7e2cad0
Revises: 3e7933877b35
Create Date: 2025-03-29 07:07:53.287093

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c6dba7e2cad0'
down_revision = '3e7933877b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'member', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'owner_id')
    # ### end Alembic commands ###
