"""Initial Migrate

Revision ID: d3139cc2802a
Revises: c6dba7e2cad0
Create Date: 2025-03-29 07:10:05.223959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3139cc2802a'
down_revision = 'c6dba7e2cad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'owner_of')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('owner_of', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
