"""Initial Migrate

Revision ID: d6e014af89e6
Revises: 1422c03177a5
Create Date: 2025-03-29 08:16:48.545829

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6e014af89e6'
down_revision = '1422c03177a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelprovider', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('modelprovider', sa.Column('team_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'modelprovider', 'team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'modelprovider', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modelprovider', type_='foreignkey')
    op.drop_constraint(None, 'modelprovider', type_='foreignkey')
    op.drop_column('modelprovider', 'team_id')
    op.drop_column('modelprovider', 'owner_id')
    # ### end Alembic commands ###
