"""Initial Migrate

Revision ID: d710f17b31ff
Revises: bd8abdf6537e
Create Date: 2025-03-29 20:21:53.128955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd710f17b31ff'
down_revision = 'bd8abdf6537e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('team_id', sa.Uuid(), nullable=False))
    op.drop_constraint('unique_team_and_name', 'member', type_='unique')
    op.create_unique_constraint('unique_team_and_name', 'member', ['name', 'team_id'])
    op.drop_constraint('member_belongs_to_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'team', ['team_id'], ['id'])
    op.drop_column('member', 'belongs_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('belongs_to', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_belongs_to_fkey', 'member', 'team', ['belongs_to'], ['id'])
    op.drop_constraint('unique_team_and_name', 'member', type_='unique')
    op.create_unique_constraint('unique_team_and_name', 'member', ['name', 'belongs_to'])
    op.drop_column('member', 'team_id')
    # ### end Alembic commands ###
