"""Initial Migrate

Revision ID: f55a6400c287
Revises: bf59240f6553
Create Date: 2025-04-01 00:21:24.102832

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f55a6400c287'
down_revision = 'bf59240f6553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'is_build')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('is_build', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
