"""initial migrate

Revision ID: f772c8d25f9b
Revises: e268f2728db0
Create Date: 2025-05-11 14:42:38.046293

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f772c8d25f9b'
down_revision = 'e268f2728db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
