nodes:
  web_search:
    flag: "enable_web_search"
    method: "web_search"
    description: "启用网络搜索功能"
    
  knowledge_retrieval:
    flag: "enable_knowledge_retrieval"
    method: "knowledge_retrieval"
    description: "启用知识库检索功能"
    
  document_generation:
    flag: "enable_document_gen"
    method: "generate_document"
    description: "启用文档生成功能"

  image_generation:
    flag: "enable_image_gen"
    method: "generate_image"
    description: "启用图片生成功能"

  code_execution:
    flag: "enable_code_execution"
    method: "execute_code"
    description: "启用代码执行功能"